# Generated by Django 3.1.7 on 2021-05-08 03:48

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Enter phone number in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
    ]
